name: TFC Manual Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'What should Terraform do?'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
      reason:
        description: 'MANDATORY: Why are you running this? (Shows in Terraform UI)'
        required: true # GitHub will mark this with a red asterisk
        type: string

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # SAFETY CHECK: If the reason is empty or just spaces, fail the build immediately
      - name: Validate Reason Input
        run: |
          if [ -z "${{ github.event.inputs.reason }}" ]; then
            echo "::error::You must provide a reason for manual execution!"
            exit 1
          fi

      - name: Zip Lambda
        run: |
          cd lambda_folder
          zip -r ../Terraform/modules/lambda_handler/payload.zip .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        working-directory: ./Terraform
        env:
          TF_VAR_TFC_RUN_MESSAGE: "${{ github.event.inputs.reason }} (by ${{ github.actor }})"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: terraform plan

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: ./Terraform
        env:
          TF_VAR_TFC_RUN_MESSAGE: "${{ github.event.inputs.reason }} (by ${{ github.actor }})"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: terraform apply -auto-approve