name: TFC CLI Deploy

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip Lambda
        run: |
          cd lambda_folder
          zip -r ../payload.zip .
          cd ..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Terraform Init & Apply
        working-directory: ./Terraform
        run: |
          terraform init
          terraform apply -auto-approve