name: TFC Manual Deploy

on:
  # Removing 'push' means it won't run when you commit code
  workflow_dispatch:
    inputs:
      action:
        description: 'What should Terraform do?'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip Lambda
        run: |
          cd lambda_folder
          zip -r ../Terraform/modules/lambda_handler/payload.zip .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init

      # Runs if you select 'plan' in the dropdown
      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        working-directory: ./Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: terraform plan

      # Runs if you select 'apply' in the dropdown
      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: ./Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: terraform apply -auto-approve